### PR TITLE
Bump version of activesupport by bumping middleman version

### PR DESCRIPTION
**Pull request by pinheadmz**
This security alert went out on github and alerted us because of a dependency: https://github.com/advisories/GHSA-2p68-f74v-9wc6

Middleman was also updated about the dependency and released a new version very quickly: https://github.com/middleman/middleman/issues/2326 

I hit some obstacles running the build with the new middleman since they upgraded from https://github.com/sass/ruby-sass to https://github.com/sass/sassc-ruby

It took me a while to finally figure out how to upgrade middleman and still render the css correctly: https://github.com/slatedocs/slate/issues/1197#issuecomment-635489124

... which is why there is a second commit to downgrade sprockets.

I'd appreciate if reviewers could test this PR on their own machines and make sure that `bin/build` (from directory root) builds everything correctly especially the api docs and make sure everything looks right, including icons and fonts.

If it works out for reviewers then we can merge this and build again.

### CODE REVIEW

**Comment by tynes** [comment]
Got an error message the first time that I tried building, but it informed me that I needed to install a different version of `bundler`. Once I did that, then `bin/build` worked fine.

Navigating through the docs site, I didn't notice differences in icons or fonts.

ACK 9f23130064cd9c3d265e1782aecc07dd0304ecbe

**Comment by pinheadmz** [comment]
@tynes your ACK is for 9f23130 but there's one other commit on this branch, e019cc584ded893f0d3a50f06564626d3d98f7a0

**Comment by tynes** [comment]
Ready to merge

ACK e019cc584ded893f0d3a50f06564626d3d98f7a0

**Comment by pinheadmz** [comment]
Thanks! 🥳

**Pull request merged**
