### PR TITLE
Update and rename index.md to index[Spanish].md

### PR DESCRIPTION
**Pull request by wimel**
Spanish translation of the index page

### CODE REVIEW

**Comment by wimel** [comment]
Translation of the installation for Linux

**Comment by hschoenburg** [comment]
Wow this is awesome. Apologies for the delay in responding.

Two things, 

First, could you update your PR to resolve the conflicts in linux-install.md and index.md?

 Second, could you rebuild the site with your changes and include the new build in your PR?
`$ ./bin/build` should do it.

Thank you!

**Comment by wimel** [comment]
Yeah, sure, I solve the problems and make the PR, about the second question, I just liked the project and I wanted to do my bit, if necessary I do something to solve it, thank you!

**Comment by pinheadmz** [comment]
Closed by 09fa623c59f1e3e60407fc309385ed3bc1b752d9

We'll have to add links to the translated pages later, but it's just nice to have them online for now.

¡GRACIAS!

**Pull request closed without merging**
